config/routes.rb
Rails.application.routes.draw do
  devise_for :users, sign_out_via: [:get, :post]
  # get 'likes/create'
  # get 'comments/create'
  resources :users do 
    resources :posts 
  end 
  resources :posts do
     resources :comments 
     resources :likes 
  end
  root to: "users#index"
  post 'authenticate', to: 'authentication#authenticate'
  namespace :api do
    resources :users do 
      resources :posts 
    end 
    resources :posts do
       resources :comments 
       resources :likes 
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, dependent: :delete_all, foreign_key: 'author_id'
  has_many :likes, dependent: :delete_all, foreign_key: 'author_id'
  has_many :comments, dependent: :delete_all, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  before_action :authenticate_request
  def index
    @users = User.all
    render json: @users, status: :ok
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
  end

  def show
    set_user
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class='nav_bar'>
  <h1>Blog App Users</h1>
  <a href="/users/sign_out" >Sign out</a>
</div>
<% @users.each do |user| %>
  <div class='users'>
    <div class='img'>
      <%= image_tag('icon.png')  %>
    </div>
    <div class='user_info'>
      <h2>Name: <%= user.name %></h2>
      <span>
      <h4>Posts:<%= user.posts_counter %></h4>
      <a id="<%=user.id%>" href='/users/<%= user.id %>'>More info</a>
      </span>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class='nav_bar'>
  <h1><%= @user.name %></h1>
  <a href="/users/sign_out" >Sign out</a>
</div>
<div class='users'>
  <div class='img'>
    <%= image_tag('icon.png')  %>
  </div>
  <div class='user_info'>
    <h1>User ID: <%= @user.id %> </h1>
    <h2 class='d-user'>Name: <%= @user.name %> </h2>
    <h3 class='d-count'>Posts:<%= @user.posts_counter%> </h3>
  </div>
</div>
<article class='bio'>
  <h4>Bio</h4>
  <p><%= @user.bio %> </p>

<%  if can? :create, Post %>
  <%= link_to "Add New Post", "/users/#{@user.id}/posts/new", {:class => "see_all_post"}%> 
<% end %>

</article>
<% @user.recent_posts.each_with_index do |post, index| %>
    <div class='d-flex bio'>
    <a id="<%=post.id%>" href='/users/<%= @user.id %>/posts'> <h3>Post # <%= index + 1 %> <%= post.title %></h3></a>
    <h4><%= post.text %></h4>

<%  if can? :destroy, Post %>
  <%= button_to 'delete post', "/users/#{@user.id}/posts/#{post.id}", method: :delete%>
<% end %>

    <h5>Comments:<%= post.comments_counter %></h5>
    <h5>Likes:<%= post.likes_counter %></h5>
    </div>
<% end %> 

<button id="all-posts" class='see'><%= link_to "See all Posts", user_posts_path(@user), {:class => "button_class"} %></button> 