config/routes.rb
Rails.application.routes.draw do
  devise_for :users, sign_out_via: [:get, :post]
  # get 'likes/create'
  # get 'comments/create'
  resources :users do 
    resources :posts 
  end 
  resources :posts do
     resources :comments 
     resources :likes 
  end
  root to: "users#index"
  post 'authenticate', to: 'authentication#authenticate'
  namespace :api do
    resources :users do 
      resources :posts 
    end 
    resources :posts do
       resources :comments 
       resources :likes 
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :delete_all, foreign_key: 'post_id'
  has_many :likes, dependent: :delete_all, foreign_key: 'post_id'

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comment
    comments.includes([:author]).last(5)
  end

  after_save :update_post_counter

  private

  def update_post_counter
    author.increment!(:posts_counter)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  before_action :authenticate_request
  def index
    @posts = Post.where(author_id: params[:user_id])
    if @posts.empty?
      json_response({ msg: 'No Posts found' }, 400)
    else
      render json: @posts
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  # before_action :set_user, only: %i[index create show]
  def index
    @user = User.find(params[:user_id])
    @posts = Post.includes(comments: [:author]).where(posts: { author_id: @user.id })
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.likes_counter = 0
    @post.comments_counter = 0
    if @post.save
      redirect_to user_posts_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.author.decrement!(:posts_counter)
    Post.delete(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_create_comments.html.erb
<%= form_with url: "/posts/#{@post.id}/comments", scope: :comments do |form| %>
  <%= form.text_area :text, placeholder: "Type something here...", rows: 10, required: true %>
  <%= form.submit "Comment" %>
<% end %>

app/views/posts/index.html.erb
<div class='nav_bar'>
  <h1><%= @user.name %>'s posts</h1>
  <a href="/users/sign_out" >Sign out</a>
</div>
<div class='users'>
  <div class='img'>
    <%= image_tag('icon.png')  %>
  </div>
  <div class='user_info'>
    <h1>User ID: <%= @user.id %> </h1>
    <h2 class='d-user'>Name: <%= @user.name %> </h2>
    <h3 class='d-count'>Posts:<%= @user.posts_counter%> </h3>
  </div>
</div>

<% @posts.each do |post| %>
  <div class='bio font'>
    <a id="<%=post.id%>" href='/users/<%= @user.id %>/posts/<%= post.id %>'><%= post.id %>: <%= post.title%></a> 
    <p><%=post.text%></p>
    <%  if can? :destroy, Post %>
  <%= button_to 'delete post', "/users/#{@user.id}/posts/#{post.id}", method: :delete%>
<% end %>


    <div class='padd'>
      <h5 id="comment<%=post.id%>">Comments: <%= post.comments_counter %></h5>
      <h5 id="like<%=post.id%>">Likes: <%= post.likes_counter %></h5>
    </div>

    <% post.comments.each do |comment| %>
      <h5><%= comment.author.name %>: <%= comment.text %> </h5>
  <% if can? :destroy, Comment %>
      <%= button_to 'delete comment', "/posts/#{post.id}/comments/#{comment.id}", method: :delete %>
  <% end %>
    <% end %>
  </div>
<% end %>

<hr/>
<button id="paginatation"><%= link_to "Pagination", "/users/#{@user.id}/posts/", {:class => "Pagination"}%></button>

app/views/posts/new.html.erb
<h1>Create a Post</h1>
<%= form_with url: user_posts_path, scope: :post do |form| %>
  <%= form.label :title, "Title" %>
  <%= form.text_field :title, placeholder: "Title", required: true%>
  <%= form.text_area :text, placeholder: "Type here...", rows: 14, required: true %>
  <%= form.submit "Post" %>
<% end %>

app/views/posts/show.html.erb
<h1>Post Details</h1>
<p><%= @post.title %> by <%= @post.author.name %> Comments <%= @post.comments_counter %>,
  Likes <%= @post.likes_counter %></p>

<p><%= @post.text %></p>

<ul>
  <% @post.comments.includes(:author).each do |comment| %>
    <p><%= comment.author.name %> : <%= comment.text %></p>
    <% if can? :destroy, comment %>
      <%= link_to "Delete Comment", user_post_comment_path(@post.author, @post, comment), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    <% end %>
  <% end %>
</ul>

<%= form_with url: "/users/#{@post.author_id}/posts/#{@post.id}/likes" do |form| %>
  <%= form.submit 'Like' %>
<% end %>
<% if can? :destroy, @post %>
  <%= link_to "Delete post", user_post_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
<% end %>
<%= link_to 'Add comment', new_user_post_comment_path(@user, @post) %>